all:
  children:
    macos:
      hosts:
        mymac:
          ansible_host: localhost
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
    linux:
      hosts:
        minibeast:
          ansible_host: minibeast
          ansible_user: "{{ lookup('env', 'MINIBEAST_SSH_USER') }}"
          ansible_ssh_pass: "{{ lookup('env', 'MINIBEAST_SSH_PASS') }}"
